cc_library (
    name = "lru_cache",
    hdrs = [
        "cache_policy.hpp",
        "cache.hpp",
        "lru_cache_policy.hpp",
    ],
    srcs = [ ],
    includes = [ ".", ],
    deps = [ ],
    copts = [ '-O2', '-Wall', '-std=c++11', ],
    linkopts = [ ],
    visibility = ["//visibility:public"],
)

